### ISSUE TITLE
"template" and "empty string.

### ISSUE THREAD

**Issue by hyber-code** [nat-davydova/webpack-config#1]
First of all thank you for the repo.

After running vanilla version of your repo i am facing following three issues.

1. ```webpack-dev-server``` is broken with the latest release of ```webpack-cli```. for the sake of testing i switched to ```webpack serve``` or simply ```webpack -w```.

2.  after fixing the first issue i am facing the following issue.

```
webpack-config@1.0.0 start D:\webdev\scripts\github\webpack-config-master
> webpack -w

[webpack-cli] ValidationError: Invalid options object. Mini CSS Extract Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'template'. These properties are valid:
   object { filename?, chunkFilename?, ignoreOrder?, insert?, attributes?, linkType? }
    at validate (D:\webdev\scripts\github\webpack-config-master\node_modules\mini-css-extract-plugin\node_modules\schema-utils\dist\validate.js:104:11)
    at new MiniCssExtractPlugin (D:\webdev\scripts\github\webpack-config-master\node_modules\mini-css-extract-plugin\dist\index.js:47:31)
    at Object.<anonymous> (D:\webdev\scripts\github\webpack-config-master\webpack.config.js:117:5)
    at Module._compile (D:\webdev\scripts\github\webpack-config-master\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\webdev\scripts\github\webpack-config-master\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at requireConfig (D:\webdev\scripts\github\webpack-config-master\node_modules\webpack-cli\lib\groups\resolveConfig.js:73:18) {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      filename: [Object],
      chunkFilename: [Object],
      ignoreOrder: [Object],
      insert: [Object],
      attributes: [Object],
      linkType: [Object]
    }
  },
  headerName: 'Mini CSS Extract Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webpack-config@1.0.0 start: `webpack -w`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webpack-config@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
the issue is 'template' for the sake of resolving this issue i commented out them from here 

```
template: `${PAGES_PUG}/${page}`,
template: `${PATHS.src}/styles/styles.scss`,
```

moving further, after commenting them out when i run ```npm start``` again i get the following error

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[4] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[4].loader should be a non-empty string.
      -> A loader request.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webpack-config@1.0.0 start: `webpack -w`
npm ERR! Exit status 2

```

so far i have reached till here.

please note: i have not changed anything from your repo.

**Comment by nat-davydova** [comment]
Hello!

I have couple of questions:

1) what do you mean 'vanilla' version? 
2) have you update anything more than cli? which version of webpack do you have?

**Comment by nat-davydova** [comment]
Ok, I've checked the issue =) I've accidentally updated package.json to weback 5 and new webpack-cli while it's a webpack 4 config. That's why it's broken.

Now I've pushed a proper package.json. Later will update the config to webpack 5 and the last webpack-cli version
